### ISSUE TITLE
Remove PromiseKit

### ISSUE THREAD

**Issue by khoi** [superarcswift/SwiftVideos#148]
I briefly look through the list of dependencies and see both `PromiseKit` and `RxSwift`. Why does the app need PromiseKit? Isn't Rx `Single` basically the same thing?

**Comment by antranapp** [comment]
I don't know much about `RxSwift` or `Single`, but the beauty of `PromiseKit` is that you can chain the async calls. I assume we can also do that with `Single` and `map` or `flatMap`. And That's why we have this ticket 😉

To be honest, I'm a very beginner when talking about `RxSwift`, only familiar with `PromiseKit`, if you could help to remove `PromiseKit` dependency by using `RxSwift`, it would be a huge help.

**Comment by antranapp** [comment]
Or we can skip `RxSwift` altogether and go straight to `Combine` using `Future` type as a replacement for `PromiseKit` 😆

**Comment by antranapp** [comment]
Haha, just found out that I've planned to remove both `RxSwift` & `PromiseKit` in another ticket already https://github.com/superarcswift/SwiftCommunity/issues/104 😬

**Comment by khoi** [comment]
great
